export const dealLabel = {
  Title: "Deal",
  Company_name: "Company Name",
  Customer_name: "Customer Name",
  Owner_mobile: "Owner Mobile",
  Inquire_number: "Inquire Number",
  PinCode: "PinCode",
  Email: "Email",
  Contract_start_date: "Contract Date",
  Contract_end_date: "Contract End Date",
  Package: "Package",
  Package_details: "Package Details",
  Month: "Month",
  Payment: "Payment",
  Payment_selection: "Payment Selection",
  Customer_address: "Customer Address",
  Listing: "If Have Listing?",
  Description: "note",
  Contract_images: "Contract Images",
  Check_images: "Check Images",
  Action : "Action"
};

export const dealKey = {
  Package: "package_id",
  Company_name: "company_name",
  Customer_name: "customer_name",
  Owner_mobile: "owner_mobile",
  Inquire_number: "inquiry_number",
  PinCode: "email",
  Email: "pin_code",
  Month: "month",
  Payment: "payment",
  Package_details: "address",
  Customer_address: "package_details",
  Payment_duration: "payment_duration",
  Listing: "is_listing",
  Description: "description",
  Contract_start_date: "contract_date",
  Contract_end_date: "contract_end_date",
  Contract_images: "contract_images",
  Check_images: "check_image",
  Status: "status",
  Profile_image: "profile_image",
};

export const DealList = [{
    "package_id": 1,
    "company_name": "Techno",
    "customer_name": "Patel",
    "owner_mobile": "9875462584",
    "inquiry_number": "9875462584",
    "email": "admin@gmail.com",
    "pin_code": "987456",
    "month": "3 month",
    "payment": 6000,
    "address": "Sola Road",
    "package_details": "3 month",
    "payment_duration": "3 month",
    "is_listing": true,
    "description": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    "contract_date": "2021-11-08",
    "contract_end_date": "2021-11-08",
    "contract_images": "User.png",
    "check_image": "User1.png",
    "status": "Open",
    "profile_image": "user.png"
  },
  {
    "package_id": 1,
    "company_name": "Techno",
    "customer_name": "Patel",
    "owner_mobile": "9875462584",
    "inquiry_number": "9875462584",
    "email": "admin@gmail.com",
    "pin_code": "987456",
    "month": "3 month",
    "payment": 6000,
    "address": "Sola Road",
    "package_details": "3 month",
    "payment_duration": "3 month",
    "is_listing": true,
    "description": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    "contract_date": "2021-11-08",
    "contract_end_date": "2021-11-08",
    "contract_images": "User.png",
    "check_image": "User1.png",
    "status": "Open",
    "profile_image": "user.png"
  },
  {
    "package_id": 1,
    "company_name": "Techno",
    "customer_name": "Patel",
    "owner_mobile": "9875462584",
    "inquiry_number": "9875462584",
    "email": "admin@gmail.com",
    "pin_code": "987456",
    "month": "3 month",
    "payment": 6000,
    "address": "Sola Road",
    "package_details": "3 month",
    "payment_duration": "3 month",
    "is_listing": true,
    "description": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    "contract_date": "2021-11-08",
    "contract_end_date": "2021-11-08",
    "contract_images": "User.png",
    "check_image": "User1.png",
    "status": "Open",
    "profile_image": "user.png"
  }
]
